spring:
  application:
    name: product-service
---
spring:
  profiles: productService1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8866/eureka/
#    registry-fetch-interval-seconds: 1
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
---
spring:
  profiles: productService2
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://app1:8888/eureka/,http://app2:8866/eureka/
#    registry-fetch-interval-seconds: 1
#  instance:
#    metadata-map:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90

