#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:${server.port}/eureka/
#
#server:
#  port: 8888

spring:
  application:
    name: eureka-service
---
spring:
  profiles: eurekaService1
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8866/eureka/
  instance:
    hostname: eurekaService1
---
spring:
  profiles: eurekaService2
server:
  port: 8866
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: eurekaService2