server:
  port: 9978

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UProcedure/config-file.git
  rabbitmq:
    host: 123.207.253.16
    port: 5672
    username: root
    password: root
    virtual-host: /java

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"