server:
  port: 9090

spring:
  application:
    name: index-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
  zipkin:
    base-url: http://localhost:8876
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#对响应和请求进行GZIP压缩
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true

##配置调用product-service服务采用的负载均衡策略
#PRODUCT-SERVICE:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG